# APP server settings
AppHost: 192.168.197.42
AppPort: 5051

#MOAS 
moas_path: '/data/LRS_det_config/moas_csv/'
db_path: '/data/LRS_det_config/lrsdetconfig.db'

#CALIB RUNS
pulser_config_path: '/data/LRS_det_config/pulser_config/Config/'
calib_data: '/data/LRS/calib_runs/'
pulser_period: 5 #ms
pulser_duration: 50 #s
